apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ac09mm982-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ac09mm982-python 
  name: ac09mm982-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ac09mm982-python 
